In [ ]:
# Import Libraries 

In [16]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.neighbors import KNeighborsRegressor # for regression purpose 
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv('./data/User_Data.csv')
df


User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

<h1>Check our Data </h1>

In [8]:
df.shape

(400, 5)

In [12]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
<h1>Feature Selection</h1>

<h1>Male and Female are text based so we need to replace those to numbers 0 and 1 </h1>

In [36]:
df['Gender']

0        Male
1        Male
2      Female
3      Female
4        Male
        ...  
395    Female
396      Male
397    Female
398      Male
399    Female
Name: Gender, Length: 400, dtype: object

In [4]:
df['Gender']=df['Gender'].replace(to_replace={'Male':1,'Female':0})
df['Gender']

0      1
1      1
2      0
3      0
4      1
      ..
395    0
396    1
397    0
398    1
399    0
Name: Gender, Length: 400, dtype: int64

In [72]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [5]:
X=df.iloc[:,1:4]
Y=df.iloc[:,4]



In [76]:
X

Gender  Age  EstimatedSalary
0         1   19            19000
1         1   35            20000
2         0   26            43000
3         0   27            57000
4         1   19            76000
..      ...  ...              ...
395       0   46            41000
396       1   51            23000
397       0   50            20000
398       1   36            33000
399       0   49            36000

[400 rows x 3 columns]

<h1>Split the data and perfrom training </h1>

In [17]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=42,test_size=0.3)

In [18]:
print("X_Train",X_train.shape ,"X-Testr",X_test.shape,"Y_train",Y_train.shape,"Y-Test",Y_test.shape)


X_Train (280, 3) X-Testr (120, 3) Y_train (280,) Y-Test (120,)


<h1>Feature Scaling   </h1>
<h3>each feature will contribute equally in decision making 
</h3>

In [19]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
X_train= st_x.fit_transform(X_train)    
X_test= st_x.transform(X_test) 

In [ ]:
<h1> Select and Train the Model </h1>

In [31]:
classifiermodel=KNeighborsClassifier(n_neighbors=3)
classifier=classifiermodel.fit(X_train,Y_train)  # Train /Fit the model with feature and output 
classifier

KNeighborsClassifier(n_neighbors=3)

<h1> Now we trained the model , so lets test the prediction on the test data(X_Test) and latter will used to Check The performance / Model Evaluation using </h1>

In [32]:
Y_Pred = classifier.predict(X_test)
Y_Pred

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0])

<h1> Sample new  Prediction</h1>

In [27]:
sample=np.array([[-0.97879618,  0.82778356, -1.43382709]])
classifier.predict(sample)

array([1])

In [33]:
#Let’s test the performance of our model – Confusion Matrix
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(Y_test, Y_Pred) 
print ("Confusion Matrix : \n", cm) 

Confusion Matrix : 
 [[68  5]
 [ 6 41]]


In [ ]:
# True +ve : correctly predicted +ves (1) 71  // 71 correcly purchase
# False +Ve : incorrect Predicted +ve(1)  2  // 2 erroly classfied 
    
# False -ve : incorrectly predicted -ves (0) 15  // errorly classified as the will not purchase 
# True -Ve : correct Predicted -ve(0)  32 // 32 correctly will not purchase
#  In general from the matrix we understand that
# 71+32 = 103 correct prediction
# 15+2  = 17 incorrect predictions 

<h1>More Model evaluation  The result for more understanding 
</h1>

In [34]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(Y_test, Y_Pred) #
precision = precision_score(Y_test, Y_Pred, pos_label=1)
recall = recall_score(Y_test, Y_Pred, pos_label=1)
f1 = f1_score(Y_test, Y_Pred, pos_label=1)

# Print the model performance metrics
print("Accuracy:", accuracy)  # 
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.9083333333333333
Precision: 0.8913043478260869
Recall: 0.8723404255319149
F1 Score: 0.8817204301075269
